srun --ntasks=1 --gres=gpu:V100:1 --cpus-per-gpu=4 --mem=32G --time=4320 \
python /scratch/kadur/src/main.py \
        --dataroot /scratch/kadur/DATA/Image \
        --n_epoch 15 \
        --n_epoch_decay 10 \
        --model BaseModel \
        --dataset PairedDataset \
        --batch_size 1 \
        --num_workers 1 \
        --load_size 320 \
        --crop_size 300 \
        --use_dis_content \
        --concat \
        --latent_dim 8 \
        --num_domains 5 \
        --d_iter 3 \
        --name basemodel_perceptual_loss \
        --save_freq 10000 \
        --print_freq 3000 \
        --display_freq 3000 \
        --vgg_loss mse \
        --vgg_layers relu5_3 \
        --vgg_type vgg19 \
        --layer_weights 1 \
        --lambda_perceptual 1 \